### ISSUE TITLE
コメントの整理 + 提出準備

### ISSUE THREAD

**Issue by YaGiNA** [PE16-mathquiz/mathquiz#16]
# 現状
- コメントが全体に対してかなり多い
- コピーしたコードに対する引用元がない

# 目標
- 説明不要なコメントを削除する
    - コードを読めばわかるもの
    - 進捗報告
    - 一時的なコメントアウト
    - etc.
- 引用元を掲載

# 参考webエントリー
https://codeiq.jp/magazine/2013/12/3700/
その他、ググればたくさん出ます

**Comment by YaGiNA** [comment]
@yamsho 

https://github.com/PE16-mathquiz/mathquiz/blob/develop/Math_quiz.java#L10

> //ここから先、コピーしたものになります。

一体何処からコピーしたのでしょうか。
引用元を掲載しなければならないのですが……

**Comment by yamsho** [comment]
前川くんが書いたやつを残したままになってて、自分がCUI用に書いたプログラムからコピーしたという意味だと思います。
消しても大丈夫だと思います。

**Comment by YaGiNA** [comment]
#21 #20 にて対応
