### ISSUE TITLE
16進数 -> 10進数問題の実装

### ISSUE THREAD

**Issue by YaGiNA** [PE16-mathquiz/mathquiz#8]
# 現状
  - 出題される問題が10進数 -> 16進数問題のみである

# やりたいこと
- 16進数(hex)から10進数(dec)に変換する問題も実装したい
  - dec -> hex（従来）とランダムで出題されるのが理想か

**Comment by yamsho** [comment]
ランダム機能を実装しました
気になる点などがあればLINEで連絡していただけると比較的すぐに反応できると思います。

**Comment by YaGiNA** [comment]
#10 で対応
